version: "3.8"

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - mysql_data:/var/lib/mysql

  # phpMyAdmin Service (User Interface)
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_gui
    restart: always
    ports:
      - "8080:80" # ব্রাউজারে ৮০৮০ পোর্টে দেখা যাবে
    environment:
      - PMA_HOST=mysql # এখানে mysql সার্ভিসটির নাম দিতে হবে
      - PMA_USER=root
      - PMA_PASSWORD=root123
    depends_on:
      - mysql

volumes:
  mysql_data: